### ISSUE TITLE
Login form demo

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow-demo#137]
- Login + password can be stored in browser
- Registration support
  - Cross field password validation
  - Password validation (N chars, M numbers, ...)

**Comment by firestormdong** [comment]
I googled a lot to find a flow login form example that browser can detect and store username+password, and finally I saw this thread.

It was marked superseded by #330, but #330 only contains registration, not login.

**Comment by Artur-** [comment]
https://github.com/vaadin/vaadin-login/issues/8 just added support for this
