### ISSUE TITLE
Create a Spring-boot demo for spring validation

### ISSUE THREAD

**Issue by caalador** [vaadin/flow-demo#465]
Create a demo using spring-boot that can be used to validate that all
required components are found for npm when not using `mvn install` 
and only starting the server with `mvn spring-boot:run`

Demo should use components where the NpmPackage is defined on 
the actual class (as `Grid`) and on a super class for example the generated 
class as is the case for vaadin-`button`.

3-rd party add-on might also be added.

Testing targets:
 - All NpmPackages were found and added to pacakge.json (if not there will be a webpack expection on runtime)
 - Should be validated with `install spring-boot:run` and `spring-boot:run`

**Comment by manolo** [comment]
> 3-rd party add-on might also be added.
This addon is already compliant with npm https://vaadin.com/directory/component/textfield-formatter/overview
